// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwloCoVVc7_wu2fDEaYrFt9QbG35sOE5Y',
    appId: '1:662269362178:web:4f9e3072cf8d699cc6271b',
    messagingSenderId: '662269362178',
    projectId: 'collab-shop-3da38',
    authDomain: 'collab-shop-3da38.firebaseapp.com',
    storageBucket: 'collab-shop-3da38.firebasestorage.app',
    measurementId: 'G-XNCNLKWHTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQoDHw_nbB6AY0mL2TBhyJyVFX60bVtI',
    appId: '1:662269362178:android:29d2da591862d718c6271b',
    messagingSenderId: '662269362178',
    projectId: 'collab-shop-3da38',
    storageBucket: 'collab-shop-3da38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpIe7_-JE61rmcP2yj_Srfr1mkUGSKMw',
    appId: '1:662269362178:ios:9d25bf4d217a7af0c6271b',
    messagingSenderId: '662269362178',
    projectId: 'collab-shop-3da38',
    storageBucket: 'collab-shop-3da38.firebasestorage.app',
    iosBundleId: 'com.example.depiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpIe7_-JE61rmcP2yj_Srfr1mkUGSKMw',
    appId: '1:662269362178:ios:9d25bf4d217a7af0c6271b',
    messagingSenderId: '662269362178',
    projectId: 'collab-shop-3da38',
    storageBucket: 'collab-shop-3da38.firebasestorage.app',
    iosBundleId: 'com.example.depiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwloCoVVc7_wu2fDEaYrFt9QbG35sOE5Y',
    appId: '1:662269362178:web:354f924d4b96a421c6271b',
    messagingSenderId: '662269362178',
    projectId: 'collab-shop-3da38',
    authDomain: 'collab-shop-3da38.firebaseapp.com',
    storageBucket: 'collab-shop-3da38.firebasestorage.app',
    measurementId: 'G-GF2W3D6T8P',
  );
}
